- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Search for all running pods
      k8s_info:
        kind: Pod
        field_selectors:
                - status.phase=Running
      register: op
    - debug:
       msg: "{{ op }}"




