- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: gcloud init
      shell: hostnamectl
      register: op
    - debug:
       msg: "{{ op }}"



